<?php
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: search.proto

namespace Magento\SearchStorefrontApi\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>magento.searchStorefrontApi.proto.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * attribute code to filer
     *
     * Generated from protobuf field <code>string attribute = 1;</code>
     */
    protected $name = '';
    /**
     * an array of values to filter on
     *
     * Generated from protobuf field <code>repeated string in = 2;</code>
     */
    private $value;
    /**
     * a string to filter on
     *
     * Generated from protobuf field <code>string eq = 3;</code>
     */
    protected $store = '';
    
    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @type string $name
     *           name to config
     * @type string $value
     *           value to config
     * @type string $store
     *           store to config
     * }
     */
    public function __construct($data = null)
    {
        \Magento\SearchStorefrontApi\Metadata\Search::initOnce();
        parent::__construct($data);
    }

    /**
     * name to config
     *
     * Generated from protobuf field <code>string name = 1;</code>
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * name to config
     *
     * Generated from protobuf field <code>string name = 1;</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * value to config
     *
     * Generated from protobuf field <code>string value = 2;</code>
     *
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * value to config
     *
     * Generated from protobuf field <code>string value = 2;</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, true);
        $this->value = $var;

        return $this;
    }

    /**
     * store to config
     *
     * Generated from protobuf field <code>string store = 3;</code>
     *
     * @return string
     */
    public function getStore()
    {
        return $this->store;
    }

    /**
     * store to config
     *
     * Generated from protobuf field <code>string store = 3;</code>
     *
     * @param  string $var
     * @return $this
     */
    public function setStore($var)
    {
        GPBUtil::checkString($var, true);
        $this->store = $var;

        return $this;
    }
}
