<?php
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: search.proto

namespace Magento\SearchStorefrontApi\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>magento.searchStorefrontApi.proto.ImportConfigRequest</code>
 */
class ImportConfigRequest extends \Google\Protobuf\Internal\Message
{
    
    /**
     * config attribute values
     *
     * Generated from protobuf field <code>repeated .magento.searchStorefrontApi.proto.Config config = 1;</code>
     */
    private $config;

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @type \Magento\SearchStorefrontApi\Proto\Config[]|\Google\Protobuf\Internal\RepeatedField $config
     *           config to import config for configuration values
     * }
     */
    public function __construct($data = null)
    {
        \Magento\SearchStorefrontApi\Metadata\Search::initOnce();
        parent::__construct($data);
    }

    /**
     * config to import config for configuration values
     *
     * Generated from protobuf field <code>repeated .magento.searchStorefrontApi.proto.Config config = 1;</code>
     *
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * config to import config for configuration values
     *
     * Generated from protobuf field <code>repeated .magento.searchStorefrontApi.proto.Config config = 1;</code>
     *
     * @param  \Magento\SearchStorefrontApi\Proto\Config[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setConfig($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Magento\SearchStorefrontApi\Proto\Config::class);
        $this->config = $arr;

        return $this;
    }
}
