<?php
// Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\SearchStorefrontApi\Api\Data;

/**
 * Autogenerated description for Config interface
 *
 * @SuppressWarnings(PHPMD.BooleanGetMethodName)
 */
interface ConfigInterface
{
    /**
     * Autogenerated description for getName() interface method
     *
     * @return string
     */
    public function getName(): string;

    /**
     * Autogenerated description for setName() interface method
     *
     * @param  string $value
     * @return void
     */
    public function setName(string $value): void;

    /**
     * Autogenerated description for getValue() interface method
     *
     * @return string
     */
    public function getValue(): string;

    /**
     * Autogenerated description for setValue() interface method
     *
     * @param  string $value
     * @return void
     */
    public function setValue(string $value): void;

    /**
     * Autogenerated description for getStore() interface method
     *
     * @return string
     */
    public function getStore(): string;

    /**
     * Autogenerated description for setStore() interface method
     *
     * @param  string $value
     * @return void
     */
    public function setStore(string $value): void;
}
