<?php
// Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\SearchStorefrontApi\Api\Data;

use Magento\Framework\ObjectManagerInterface;

/**
 * Autogenerated description for ImportConfigRequest class
 *
 * @SuppressWarnings(PHPMD.CouplingBetweenObjects)
 * @SuppressWarnings(PHPMD.CyclomaticComplexity)
 * @SuppressWarnings(PHPMD.UnusedPrivateField)
 * @SuppressWarnings(PHPMD.NPathComplexity)
 * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
 */
final class ImportConfigRequestArrayMapper
{
    /**
     * @var mixed
     */
    private $data;

    /**
     * @var ObjectManagerInterface
     */
    private $objectManager;

    public function __construct(ObjectManagerInterface $objectManager)
    {
        $this->objectManager = $objectManager;
    }

    /**
     * Convert the DTO to the array with the data
     *
     * @param  ImportConfigRequest $dto
     * @return array
     */
    public function convertToArray(ImportConfigRequest $dto)
    {
        $result = [];
        
        /**
         * Convert complex Array field
        **/
        $fieldArray = [];
        foreach ($dto->getConfig() as $fieldArrayDto) {
            $fieldArray[] = $this->objectManager->get(\Magento\SearchStorefrontApi\Api\Data\ConfigArrayMapper::class)
                ->convertToArray($fieldArrayDto);
        }
        $result["config"] = $fieldArray;
        
        return $result;
    }
}
