<?php
// Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\SearchStorefrontApi\Api\Data;

/**
 * Autogenerated description for ImportConfigRequest class
 *
 * phpcs:disable Magento2.PHP.FinalImplementation
 *
 * @SuppressWarnings(PHPMD)
 * @SuppressWarnings(PHPCPD)
 */
final class ImportConfigRequest implements ImportConfigRequestInterface
{

    /**
     * @var array
     */
    private $config;
    
    /**
     * @inheritdoc
     *
     * @return \Magento\SearchStorefrontApi\Api\Data\ConfigInterface[]
     */
    public function getConfig(): array
    {
        return (array) $this->config;
    }
    
    /**
     * @inheritdoc
     *
     * @param  \Magento\SearchStorefrontApi\Api\Data\ConfigInterface[] $value
     * @return void
     */
    public function setConfig(array $value): void
    {
        $this->config = $value;
    }
}
