<?php
// Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\SearchStorefrontApi\Api\Data;

/**
 * Autogenerated description for ImportConfigRequest interface
 *
 * @SuppressWarnings(PHPMD.BooleanGetMethodName)
 */
interface ImportConfigRequestInterface
{
    /**
     * Autogenerated description for getConfig() interface method
     *
     * @return \Magento\SearchStorefrontApi\Api\Data\ConfigInterface[]
     */
    public function getConfig(): array;

    /**
     * Autogenerated description for setConfig() interface method
     *
     * @param  \Magento\SearchStorefrontApi\Api\Data\ConfigInterface[] $value
     * @return void
     */
    public function setConfig(array $value): void;
}
